name: bypass_app
description: A smart delivery and ride-sharing platform for Oman.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  image_picker: ^0.8.7
  intl: ^0.17.0
  shared_preferences: ^2.1.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  http: ^0.13.5
  flutter_svg: ^2.0.4
  url_launcher: ^6.1.10

  # Firebase packages are commented out because we're using a mock implementation
  # Uncomment these for real Firebase functionality
  # firebase_core: ^1.10.0
  # firebase_auth: ^3.3.0
  # firebase_database: ^9.0.0
  # firebase_storage: ^10.2.0
  # cloud_firestore: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Add or modify the assets section like this:
  assets:
    - assets/ # This includes all files in the assets folder
    # OR specifically:
    # - assets/bypass_logo.png
    # If you have fonts, keep their declarations as well:
    # - assets/fonts/

  # Keep your fonts section if you have one
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300
